### ISSUE TITLE
Droste Effect Page seems broken?

### ISSUE THREAD

**Issue by no-identd** [montaga/montaga.github.io#2]
Recently I used it and it worked fine, now it seems completely broken?

**Comment by montaga** [comment]
Maybe it works now?
Which browser are you using and does the problem only occur if a camera is accessed?

**Comment by no-identd** [comment]
Thanks, works now! Occurred in all browsers I had tried, and independent of if the camera got accessed. (In fact, the PC I tried it on doesn't have a webcam.)
